### ISSUE TITLE
[Feature Request] Equirectangular (360deg) output

### ISSUE THREAD

**Issue by burritosoftware** [kinsi55/CS_BeatSaber_Camera2#26]
Equirectangular projection output would allow for recording or streaming equirectangular video source which allows for viewers on the web to pan around with their mouse or by tilting their phone, or by using a VR headset like Cardboard or the YouTube VR app.

Examples of using this can be for streaming a 3rd person view of your playthrough where your live viewers can look around and change their angle (YouTube supports equirectangular streaming), or sharing clips and replays to your audience, family, or friends where they can rotate their phone to look around in the VR space.

**Comment by kinsi55** [comment]
For more reasons than one I don't think adding this to camera2 is worth it:

- All the action happens in front of you
- it requires a lot of processing power since you need to render 6 cameras
- you need a high resolution screen to make any use of this as otherwise the resulting view would be low resolution

You can always go ahead and do this manually by creating the necessary cameras and aligning them by editing the configs but I think this is too niche of a feature for me to consider adding it into cam2

**Comment by kinsi55** [comment]
As there doesn't seem to be any counter arguments I'm closing (for now)
