### ISSUE TITLE
First-person camera position/rotation offset

### ISSUE THREAD

**Issue by Reselim** [kinsi55/CS_BeatSaber_Camera2#34]
One pretty critical feature that I've missed when going from CameraPlus to Camera2 is the ability to change the positional and rotational offset relative to the HMD center. This is particularly bad for me because I [tend to rotate my HMD upwards unintentionally](https://www.twitch.tv/videos/1031158371) on more strenuous maps, leading to an uncomfortable viewing experience.

I've tried looking all over the wiki and config files and I can't seem to find anything — I don't think this would be too hard to implement, though.

**Comment by kinsi55** [comment]
You can edit the targetpos and targetrot in the config file. Only the targetpos' z value is exposed in the settings UI because having all values there would clutter the UI quite a bit as well as being of no use to most.

https://github.com/kinsi55/CS_BeatSaber_Camera2/wiki/Camera-Configuration#targetpos--targetrot

**Comment by Reselim** [comment]
Interesting. I had tried changing it, but it must have not worked without a restart. Either way, this issue has been solved. Thanks!
