### ISSUE TITLE
fitToCanvas option missing

### ISSUE THREAD

**Issue by Carsans-Scantling** [kinsi55/CS_BeatSaber_Camera2#61]
When my friend uses Camera2, the window is stuck in the bottom left corner. In the previous camera mod "CameraPlus", this was fixed using a setting called "fitToCanvas". However, this setting is apparent no where we can find (checked in game settings, checked the configs, can't edit the .dll, checked every folder in Beat Saber). This makes streaming to discord an extreme issue. I have no clue if this is a bug, if we're missing something, or if the feature was renamed/changed. Either way this problem is extremely inhibiting the use of this mod and we would appreciate some input related to changing the camera size in the Beat Saber application (all we currently see is a small window in the bottom left and a black background behind it.

Config file is attached.

[Static_Thirdperson.zip](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/7967844/Static_Thirdperson.zip)

**Comment by kinsi55** [comment]
fitToCanvas does not exist in Cam2 because it is not necessary. In CameraPlus, the positions and sizes of the cameras on the desktop are configured as pixels - In Camera2 they are fractions of a whole, so if you have a camera which has x: 0, y: 0, width: 1, height: 1 it is a camera that fits the entire screen
