### ISSUE TITLE
Sabers not moving with the camera

### ISSUE THREAD

**Issue by Drahy** [kinsi55/CS_BeatSaber_Camera2#7]
Hello,

Is there any option to move sabers as well as the camera for example in noodle extensions?

See here at the begining of the video: https://www.youtube.com/watch?v=ABq-jV0KrMI

**Comment by kinsi55** [comment]
This should not be an issue related to Camera2 - Camera2 just has a Feature in it that causes cameras to follow the map rotation, if anything else happens to not follow the map rotation that is an issue of whatever Plugin is responsible for that object.

Since you're having an Avatar, I guess you're probably using VMC in combination with the VMC plugin that makes it follow map rotation? If so that is probably whats causing the issue.
