### ISSUE TITLE
Ability to disable cameras ingame to save performance

### ISSUE THREAD

**Issue by blackorbit1** [kinsi55/CS_BeatSaber_Camera2#87]
Depending on what you want to do, you can sometimes need a scripted camera, sometimes a normal third person camera, sometimes a 1st person, etc.
You can have all of them at the same time and just change the order of the layers depending on your needs but each camera, even hidden will still have a performance cost (that can become huge, depending on the computer and the number of cameras).

Maybe having the ability to disable cameras ingame could fix this issue without having to change the camera file name extensions to hide it to camera2.

Here's a quick idea of what it could look like:
![image](https://user-images.githubusercontent.com/38140797/190105914-f5010d9d-d846-492d-aa82-77218c2f5546.png)

**Comment by kinsi55** [comment]
To accomplish this you are supposed to use [Scenes](https://github.com/kinsi55/CS_BeatSaber_Camera2/wiki/Scenes) / [Custom Scenes](https://github.com/kinsi55/CS_BeatSaber_Camera2/wiki/Scenes#custom-scenes).

When not using scenes, all cameras are active at all times, but as soon as even one camera is assigned to a scene (used at that point) others are disabled

**Comment by blackorbit1** [comment]
It feels a bit like a trick when all the cameras are meant for the playing scene but yeah in the end the result is the same.

Maybe this is still relevant for really simple use cases when the user have a few cameras and just want to use one for recording gameplays at a time or more complex use case with a streamer for example with a ton of cameras and scene that want to test / compare cameras or have like 2 setups for different use case.

**Comment by kinsi55** [comment]
I dont want to have multiple different ways of selectively enabling / disabling cameras as that is just bound to cause confusion. I was going to rework custom scenes at some point so that they rather work more like profiles, where the cameras in that profile will stil respect the scene they are assigned to, but you can selectively only enable a specific set of cameras but I didnt get around to that. In the simplest use case that would still work the same as a custom scene but allows for more flexible uses, like what you describe.

**Comment by blackorbit1** [comment]
oh ok, I think that would be the best solution indeed 👍

**Comment by kinsi55** [comment]
In that case, I will close this for now 👍
